import { useState } from 'react';
import { Check, ClipboardCopy, FileJson, Loader2, Sparkles } from 'lucide-react';
import BackButton from '@/components/BackButton';
import { useAuth } from '@/hooks/useAuth';
import { useDeckLibrary } from '@/hooks/useDeckLibrary';
import { parseTaggedImport, type TaggedImportEntry } from '@/lib/import-tagged';
import { IMPORT_PROMPT, importIntoNewDeck, nextAddedWordsTitle } from '@/lib/added-words';

/**
 * Bringing words in from outside, from Settings and nowhere else.
 *
 * Two ways in that differ only in where the JSON came from — pasted straight,
 * or generated by the learner's own Claude from the prompt below — so both
 * run through the same validator and land the same way: their own deck, and
 * their words into the shared bank.
 *
 * Nothing is written until the preview has been seen. An import is dozens of
 * rows at once, and a silent commit of a bad paste is tedious to unpick.
 */
const ImportWords = ({ onBack }: { onBack: () => void }) => {
  const { user } = useAuth();
  const { decks, refresh } = useDeckLibrary();
  const [text, setText] = useState('');
  const [entries, setEntries] = useState<TaggedImportEntry[] | null>(null);
  const [errors, setErrors] = useState<string[]>([]);
  const [busy, setBusy] = useState(false);
  const [done, setDone] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const mine = decks.filter((d) => d.createdBy === user?.id);
  const nextTitle = nextAddedWordsTitle(mine.map((d) => d.title));

  const check = () => {
    setDone(null);
    const result = parseTaggedImport(text);
    setEntries(result.entries);
    setErrors(result.errors);
  };

  const commit = async () => {
    if (!entries || entries.length === 0 || !user) return;
    setBusy(true);
    try {
      const { deck, words } = await importIntoNewDeck(
        entries,
        user.id,
        mine.map((d) => d.title),
        decks.map((d) => d.icon),
      );
      setDone(`${words} word${words === 1 ? '' : 's'} added to “${deck.title}”.`);
      setEntries(null);
      setText('');
      setErrors([]);
      await refresh();
    } catch (err) {
      setErrors([err instanceof Error ? err.message : 'The import could not be saved.']);
    } finally {
      setBusy(false);
    }
  };

  const copyPrompt = async () => {
    try {
      await navigator.clipboard.writeText(IMPORT_PROMPT);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard access can be refused; the prompt is on screen to select.
      setCopied(false);
    }
  };

  return (
    <div className="space-y-4">
      <BackButton onClick={onBack} label="Settings" />

      <div className="space-y-1">
        <h2 className="text-xl font-bold text-foreground">Import words</h2>
        <p className="text-sm text-muted-foreground">
          Each import becomes its own deck, which you can rename afterwards. The next one will be
          called “{nextTitle}”.
        </p>
      </div>

      {done && (
        <p className="flex items-center gap-1.5 rounded-xl bg-success/10 px-4 py-3 text-sm font-medium text-success">
          <Check className="h-4 w-4 shrink-0" />
          {done}
        </p>
      )}

      <section className="space-y-2 rounded-2xl border border-border bg-card p-4">
        <p className="flex items-center gap-1.5 text-sm font-medium text-foreground">
          <Sparkles className="h-4 w-4 text-primary" />
          Have your own Claude format a list
        </p>
        <p className="text-xs text-muted-foreground">
          Copy this prompt, paste it into Claude followed by your vocabulary, then paste what it
          returns into the box below.
        </p>
        <button
          onClick={copyPrompt}
          className="flex w-full items-center justify-center gap-1.5 rounded-xl bg-primary py-2.5 text-sm font-semibold text-primary-foreground transition-all active:scale-95"
        >
          {copied ? <Check className="h-4 w-4" /> : <ClipboardCopy className="h-4 w-4" />}
          {copied ? 'Copied' : 'Copy the prompt'}
        </button>
        <details className="text-xs text-muted-foreground">
          <summary className="cursor-pointer select-none">See the prompt</summary>
          <pre className="mt-2 max-h-40 overflow-y-auto whitespace-pre-wrap rounded-lg bg-muted/40 p-2 text-[11px] leading-relaxed">
            {IMPORT_PROMPT}
          </pre>
        </details>
      </section>

      <section className="space-y-2 rounded-2xl border border-border bg-card p-4">
        <label htmlFor="import-json" className="flex items-center gap-1.5 text-sm font-medium text-foreground">
          <FileJson className="h-4 w-4 text-primary" />
          Paste the JSON
        </label>
        <p className="text-xs text-muted-foreground">
          A JSON array where each entry has <code>fusha</code> and <code>english</code>, and
          optionally a root, form, plural, verb parts and word family.
        </p>
        <textarea
          id="import-json"
          value={text}
          onChange={(e) => setText(e.target.value)}
          rows={8}
          placeholder='[{"fusha": "…", "english": "…"}]'
          dir="ltr"
          className="w-full rounded-xl border border-border bg-background px-3 py-2 font-mono text-xs focus:outline-none focus:ring-2 focus:ring-primary/30"
        />
        <button
          onClick={check}
          disabled={!text.trim()}
          className="w-full rounded-xl border border-primary py-2.5 text-sm font-semibold text-primary transition-all active:scale-95 disabled:opacity-40"
        >
          Check it
        </button>
      </section>

      {errors.length > 0 && (
        <div className="space-y-1 rounded-xl border border-destructive/40 bg-destructive/5 px-4 py-3">
          <p className="text-sm font-medium text-destructive">
            {errors.length} problem{errors.length === 1 ? '' : 's'} found
          </p>
          <ul className="space-y-0.5 text-xs text-destructive">
            {errors.slice(0, 12).map((e, i) => (
              <li key={i}>{e}</li>
            ))}
          </ul>
          {errors.length > 12 && (
            <p className="text-xs text-destructive/80">…and {errors.length - 12} more.</p>
          )}
        </div>
      )}

      {entries && entries.length > 0 && (
        <section className="space-y-2 rounded-2xl border border-border bg-card p-4">
          <p className="text-sm font-medium text-foreground">
            {entries.length} word{entries.length === 1 ? '' : 's'} ready
          </p>
          <div className="max-h-64 overflow-y-auto rounded-xl border border-border divide-y divide-border/60">
            {entries.map((e, i) => (
              <div key={i} className="flex items-baseline justify-between gap-3 px-3 py-2">
                <span className="min-w-0 flex-1 truncate text-xs text-muted-foreground">
                  {e.english}
                  {e.root && <span className="font-arabic"> · {e.root}</span>}
                </span>
                <span className="font-arabic text-base text-foreground" dir="rtl">
                  {e.wordVoweled || e.fusha}
                </span>
              </div>
            ))}
          </div>
          <button
            onClick={commit}
            disabled={busy}
            className="flex w-full items-center justify-center gap-1.5 rounded-xl bg-primary py-3 font-semibold text-primary-foreground transition-all active:scale-95 disabled:opacity-50"
          >
            {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />}
            Add them to “{nextTitle}”
          </button>
          <p className="text-[11px] text-muted-foreground">
            The words also go into the shared bank so others can find them. The deck itself stays
            private to you.
          </p>
        </section>
      )}
    </div>
  );
};

export default ImportWords;
