// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-flashcards.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function clientFor(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_flashcards_default = defineTool({
  name: "list_flashcards",
  title: "List flashcards",
  description: "List the signed-in user's Arabic flashcards. Optionally filter by a substring match on the Arabic word or English translation.",
  inputSchema: {
    search: z.string().optional().describe("Optional case-insensitive substring to match against the Arabic word or English translation."),
    limit: z.number().int().min(1).max(500).optional().describe("Maximum number of cards to return. Defaults to 100.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = clientFor(ctx).from("flashcards").select("id, word, english, next_review_date, interval_days, ease_factor, learning_stage, word_type, verb_form, root").order("created_at", { ascending: false }).limit(limit ?? 100);
    if (search && search.trim()) {
      const s = search.trim().replace(/[%,]/g, "");
      q = q.or(`word.ilike.%${s}%,english.ilike.%${s}%`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { cards: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-flashcard.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function clientFor2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_flashcard_default = defineTool2({
  name: "create_flashcard",
  title: "Create flashcard",
  description: "Create a new Arabic flashcard for the signed-in user with an Arabic word and its English translation.",
  inputSchema: {
    word: z2.string().trim().min(1).describe("The Arabic word."),
    english: z2.string().trim().min(1).describe("The English translation."),
    image_url: z2.string().url().optional().describe("Optional image URL to display with the card.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ word, english, image_url }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const today = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    const { data, error } = await clientFor2(ctx).from("flashcards").insert({
      user_id: ctx.getUserId(),
      word,
      english,
      image_url: image_url ?? null,
      next_review_date: today,
      interval_days: 0,
      ease_factor: 2.5,
      learning_stage: "new",
      stage1_attempts: 0,
      stage2_attempts: 0
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created card ${data.id}: ${data.word} \u2014 ${data.english}` }],
      structuredContent: { card: data }
    };
  }
});

// src/lib/mcp/tools/get-due-cards.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function clientFor3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_due_cards_default = defineTool3({
  name: "get_due_cards",
  title: "Get cards due for review",
  description: "List the flashcards that are due for spaced-repetition review today or earlier for the signed-in user.",
  inputSchema: {
    limit: z3.number().int().min(1).max(500).optional().describe("Maximum number of cards to return. Defaults to 100.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const today = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    const { data, error } = await clientFor3(ctx).from("flashcards").select("id, word, english, next_review_date, interval_days, ease_factor, learning_stage").lte("next_review_date", today).neq("learning_stage", "new").order("next_review_date", { ascending: true }).limit(limit ?? 100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { cards: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/delete-flashcard.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function clientFor4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var delete_flashcard_default = defineTool4({
  name: "delete_flashcard",
  title: "Delete flashcard",
  description: "Permanently delete one of the signed-in user's flashcards by id.",
  inputSchema: {
    id: z4.string().uuid().describe("The flashcard id to delete.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { error } = await clientFor4(ctx).from("flashcards").delete().eq("id", id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Deleted card ${id}` }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fphpcfecgnfoogfaeihu";
var mcp_default = defineMcp({
  name: "arabic-flashcards-mcp",
  title: "Arabic Flashcards",
  version: "0.1.0",
  instructions: "Tools for the user's Arabic flashcard deck. Use list_flashcards to browse cards, get_due_cards to see what is due for spaced-repetition review today, create_flashcard to add new Arabic/English words, and delete_flashcard to remove one. All actions are scoped to the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_flashcards_default, get_due_cards_default, create_flashcard_default, delete_flashcard_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
